### ISSUE TITLE
Simon the Sorcerer II - The Lion, the Wizard and the Wardrobe (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2773] opened 2021-04-11 15:54 UTC
Just read this comment by NRS:

"Simon the Sorcerer II has two sets of MIDI files: MT-32 and General MIDI. The MT-32 MIDI files are played if there is a file named "MIDI" in the directory, otherwise the General MIDI files are played. The SETUP program creates the file "MIDI" when selecting either MT-32 or General MIDI, even as it should only create it with MT-32. Solution: delete the "MIDI" file when selecting General MIDI. Apart from that problem, I know of no problems with the MIDPAK drivers. Which one is the original synth? Difficult to say; the MT-32 versions differ from the General MIDI ones in some cases, seemingly being earlier versions. On the other hand, some songs are completely missing on MT-32, such as during the intro when Runt talks to his father."

Our exodos setup has the MIDI file in both MT32 and SC55 folders.

**Comment by exoscoriae** [comment] 2021-04-28 20:07
this seems like a duplicate of:
https://github.com/exoscoriae/eXoDOS/issues/2785

Closing until further comments suggest this is a unique issue.

**Closed by exoscoriae** 2021-04-28 20:07 UTC
Labels: bug
