### ISSUE TITLE
Overlord 1994

### ISSUE THREAD

**Issue by bcol80** [exoscoriae/eXoDOS#3114] opened 2021-07-25 12:37 UTC
Missing manual. When you click on the manual option in LB you get the manual for the 1990 RTS Overlord game instead.

**Comment by TimberlAndRE-de** [comment] 2021-07-25 12:54
confirmed
It's because of fuzzy Launchbox logic finds the wrong manual in the \Manuals folder!

You can fix it yourself (until it's fixed in next release):
- edit the Overlord (1994) entry in Launchbox
- click on "Media" and change `Manuals\MS-DOS\Overlord (1990).pdf` to `Manuals\MS-DOS\Overlord (1994).pdf`

@exoscoriae maybe set the manual manually ;-) in the XML for next release?

**Comment by exoscoriae** [comment] 2021-07-26 17:30
now that we have both manuals, this is no longer an issue

**Closed by exoscoriae** 2021-07-26 17:30 UTC
Labels: bug
