### ISSUE TITLE
Street Sports Baseball (1987)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1173] opened 2020-07-11 18:32 UTC
The game begins automatically without menu to select the teams and the numbers of players.
Here is a version that works correctly : https://www.old-games.ru/game/download/3633.html

**Comment by exoscoriae** [comment] 2020-07-11 22:55
the files are identical. the issue is the conf wasn't calling the bat file. thanks though. it is fixed now

**Closed by exoscoriae** 2020-07-11 22:55 UTC
Labels: bug
